const {onRequest}=require('firebase-functions/v2/https');
const admin=require('firebase-admin');
const cheerio=require('cheerio');
admin.initializeApp();
Object.assign(exports,require('./workouts'));
const DEFAULT_ATHLETE_ID='';
const geocodeCache=new Map();
const knownCities={ventasso:{lat:44.365,lon:10.333},'castelvetro di modena':{lat:44.504,lon:10.946},'reggio nell\u0027emilia':{lat:44.698,lon:10.631},'reggio emilia':{lat:44.698,lon:10.631},castellarano:{lat:44.555,lon:10.733},boretto:{lat:44.902,lon:10.555},novellara:{lat:44.845,lon:10.727},gualtieri:{lat:44.904,lon:10.629},rubiera:{lat:44.653,lon:10.782},modena:{lat:44.648,lon:10.926},casalgrande:{lat:44.598,lon:10.734},bologna:{lat:44.494,lon:11.342},parma:{lat:44.801,lon:10.328},ravenna:{lat:44.418,lon:12.204},milano:{lat:45.464,lon:9.19},roma:{lat:41.9028,lon:12.4964},torino:{lat:45.0703,lon:7.6869},genova:{lat:44.4056,lon:8.9463},firenze:{lat:43.7696,lon:11.2558},verona:{lat:45.4384,lon:10.9916},padova:{lat:45.4064,lon:11.8768},venezia:{lat:45.4408,lon:12.3155},napoli:{lat:40.8518,lon:14.2681},bari:{lat:41.1171,lon:16.8719},palermo:{lat:38.1157,lon:13.3615},rimini:{lat:44.0678,lon:12.5695},ferrara:{lat:44.8381,lon:11.6198},'reggio calabria':{lat:38.1113,lon:15.6473},cesena:{lat:44.1391,lon:12.2431},forli:{lat:44.2227,lon:12.0407},brescia:{lat:45.5416,lon:10.2118},bergamo:{lat:45.6983,lon:9.6773}};
async function geocode(city){if(geocodeCache.has(city))return geocodeCache.get(city);const normalized=city.toLowerCase().trim();if(knownCities[normalized]){geocodeCache.set(city,knownCities[normalized]);return knownCities[normalized]}const fallback={lat:44.65,lon:11.1};try{const r=await fetch(`https://photon.komoot.io/api/?limit=1&lang=it&q=${encodeURIComponent(`${city}, Italia`)}`,{headers:{'User-Agent':'RunMap/1.0'}});if(!r.ok)return fallback;const data=await r.json();const coordinates=data.features?.[0]?.geometry?.coordinates;const point=coordinates?{lat:Number(coordinates[1]),lon:Number(coordinates[0])}:fallback;geocodeCache.set(city,point);return point}catch(error){console.error(`Geocoding fallito per ${city}`,error);return fallback}}
async function suggestCities(query){const normalized=query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,' ').replace(/\s+/g,' ').trim();try{const r=await fetch(`https://photon.komoot.io/api/?limit=6&lang=it&q=${encodeURIComponent(`${query}, Italia`)}`,{headers:{'User-Agent':'RunMap/1.0'}});if(r.ok){const data=await r.json();const results=(data.features||[]).map(feature=>{const p=feature.properties;return {label:[p.name,p.city||p.town||p.village,p.state].filter((item,index,array)=>item&&array.indexOf(item)===index).join(', '),lat:feature.geometry.coordinates[1],lon:feature.geometry.coordinates[0]}});if(results.length)return results}}catch(error){console.error('Photon non disponibile',error)}return Object.entries(knownCities).filter(([name])=>name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,' ').replace(/\s+/g,' ').includes(normalized)).slice(0,6).map(([name,point])=>({label:name.replace(/\b\w/g,letter=>letter.toUpperCase()),...point}))}
function parseTime(value){return value.replace(/\./g,':').match(/\b\d{2}:\d{2}:\d{2}\b/)?.[0]||'00:00:00'}
exports.citySuggestions=onRequest({cors:true,region:'europe-west1'},async(req,res)=>{if(req.method!=='GET')return res.status(405).json({error:'GET required'});if(!req.headers.authorization?.startsWith('Bearer '))return res.status(401).json({error:'Login richiesto'});try{const query=String(req.query.q||'').trim();if(query.length<3)return res.json({cities:[]});return res.json({cities:await suggestCities(query)})}catch(error){console.error(error);return res.status(502).json({error:'Suggerimenti non disponibili'})}});
exports.importRaces=onRequest({cors:true,region:'europe-west1',timeoutSeconds:60},async(req,res)=>{if(req.method!=='GET')return res.status(405).json({error:'GET required'});if(!req.headers.authorization?.startsWith('Bearer '))return res.status(401).json({error:'Login richiesto'});const athleteId=String(req.query.athleteId||DEFAULT_ATHLETE_ID).trim();if(!athleteId||!/^[0-9]+$/.test(athleteId))return res.status(400).json({error:'Codice atleta non valido'});try{const response=await fetch(`https://www.irunning.it/atleta.php?id=${athleteId}`,{headers:{'User-Agent':'RunMap/1.0'}});if(!response.ok)throw new Error(`iRunning ${response.status}`);const $=cheerio.load(await response.text());const athleteName=$('h1').first().text().replace(/atleta|profilo/gi,'').trim()||$('title').text().split('|')[0].trim();const races=[];const activityTable=$('table.responstable').filter((i,table)=>{const headings=$(table).find('thead th').map((n,th)=>$(th).text().trim().toLowerCase()).get();return headings.includes('data')&&headings.includes('località')&&headings.includes('gara')&&headings.includes('ris.')}).first();activityTable.find('tbody tr').each((index,row)=>{const cells=$(row).find('td');if(cells.length<7)return;const dateRaw=$(cells[0]).text().trim();const parts=dateRaw.split('/');if(parts.length!==3)return;const city=$(cells[1]).text().trim().replace(/\s+/g,' ').toLowerCase();const raceCell=$(cells[2]).text().replace(/\s+/g,' ').trim();const name=$(cells[2]).find('a').first().text().trim()||raceCell.replace(/SPECIALIT.*/i,'').trim();const typeMatch=raceCell.match(/SPECIALIT.\s*:\s*([^]+)$/i);const raceType=typeMatch?typeMatch[1].trim().toLowerCase():null;const placing=$(cells[7]).text().replace(/\s+/g,' ').trim();const absoluteMatch=placing.match(/(\d+)\s*\(ASS\)/i);const absolutePlace=absoluteMatch?Number(absoluteMatch[1]):null;const time=parseTime($(cells[6]).text().trim());const distanceMatch=name.match(/(\d+(?:[.,]\d+)?)\s*km/i);const distance=distanceMatch?Number(distanceMatch[1].replace(',','.')):null;races.push({id:`irunning-${athleteId}-${index}-${parts.join('')}`,date:`${parts[2]}-${parts[1].padStart(2,'0')}-${parts[0].padStart(2,'0')}`,name,city,raceType,absolutePlace,distance,time,lat:null,lon:null,notes:'',photos:[]})});for(const race of races){const point=await geocode(race.city);race.lat=point.lat;race.lon=point.lon}return res.json({athleteId,athleteName,races})}catch(error){console.error(error);return res.status(502).json({error:'Importazione iRunning non riuscita'})}});

const crypto=require('crypto');
const STRAVA_AUTHORIZE='https://www.strava.com/oauth/authorize';
const STRAVA_TOKEN='https://www.strava.com/oauth/token';
const STRAVA_ACTIVITIES='https://www.strava.com/api/v3/athlete/activities';
const oauthState=(payload)=>{const value=Buffer.from(JSON.stringify(payload)).toString('base64url');const signature=crypto.createHmac('sha256',process.env.STRAVA_CLIENT_SECRET||'').update(value).digest('base64url');return `${value}.${signature}`};
const readOAuthState=(state)=>{const [value,signature]=String(state||'').split('.');if(!value||!signature)return null;const expected=crypto.createHmac('sha256',process.env.STRAVA_CLIENT_SECRET||'').update(value).digest('base64url');const actualBuffer=Buffer.from(signature),expectedBuffer=Buffer.from(expected);if(actualBuffer.length!==expectedBuffer.length||!crypto.timingSafeEqual(actualBuffer,expectedBuffer))return null;const payload=JSON.parse(Buffer.from(value,'base64url').toString());if(!payload.uid||!payload.createdAt||Date.now()-payload.createdAt>10*60*1000)return null;return payload};
const bearerUser=async req=>{const header=req.headers.authorization||'';if(!header.startsWith('Bearer '))return null;try{return await admin.auth().verifyIdToken(header.slice(7))}catch{return null}};
exports.stravaAuth=onRequest({cors:true,region:'europe-west1',invoker:'public'},async(req,res)=>{const decoded=await bearerUser(req);if(!decoded)return res.status(401).json({error:'Login richiesto'});if(!process.env.STRAVA_CLIENT_ID||!process.env.STRAVA_CLIENT_SECRET||!process.env.STRAVA_REDIRECT_URI)return res.status(500).json({error:'Configurazione Strava mancante'});const state=oauthState({uid:decoded.uid,createdAt:Date.now()});const params=new URLSearchParams({client_id:process.env.STRAVA_CLIENT_ID,response_type:'code',redirect_uri:process.env.STRAVA_REDIRECT_URI,approval_prompt:'auto',scope:'read,activity:read_all',state});res.json({authorizationUrl:`${STRAVA_AUTHORIZE}?${params}`})});
exports.stravaCallback=onRequest({cors:true,region:'europe-west1',timeoutSeconds:60,invoker:'public'},async(req,res)=>{try{const state=readOAuthState(req.query.state);if(!state)return res.status(400).send('Stato OAuth non valido o scaduto.');if(req.query.error)return res.redirect(`${process.env.RUNMAP_APP_URL||'/'}?strava=cancelled`);const tokenResponse=await fetch(STRAVA_TOKEN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:process.env.STRAVA_CLIENT_ID,client_secret:process.env.STRAVA_CLIENT_SECRET,code:req.query.code,grant_type:'authorization_code'})});if(!tokenResponse.ok)throw new Error(`Strava token ${tokenResponse.status}`);const token=await tokenResponse.json();await admin.firestore().doc(`users/${state.uid}/integrations/strava`).set({accessToken:token.access_token,refreshToken:token.refresh_token,expiresAt:token.expires_at,athlete:token.athlete||null,updatedAt:Date.now()});let imported=0;let page=1;while(page<=10){const activitiesResponse=await fetch(`${STRAVA_ACTIVITIES}?per_page=200&page=${page}`,{headers:{Authorization:`Bearer ${token.access_token}`}});if(!activitiesResponse.ok)throw new Error(`Strava activities ${activitiesResponse.status}`);const activities=await activitiesResponse.json();if(!activities.length)break;const batch=admin.firestore().batch();activities.filter(a=>['Run','VirtualRun','TrailRun'].includes(a.type)).forEach(activity=>{const id=`strava-${activity.id}`;batch.set(admin.firestore().doc(`users/${state.uid}/workouts/${id}`),{id,name:activity.name||'Attività Strava',date:String(activity.start_date_local||activity.start_date).slice(0,10),distance:Number(activity.distance||0)/1000,source:'strava',stravaId:String(activity.id),updatedAt:Date.now()},{merge:true});imported++});await batch.commit();if(activities.length<200)break;page++}res.redirect(`${process.env.RUNMAP_APP_URL||'/'}?strava=connected&imported=${imported}`)}catch(error){console.error('Strava OAuth failed',error);res.redirect(`${process.env.RUNMAP_APP_URL||'/'}?strava=error`)}});

// Espone in modo definitivo il modulo nuovo delle attività.
Object.assign(exports,require('./workouts'));
