const {onRequest}=require('firebase-functions/v2/https');
const admin=require('firebase-admin');
const cheerio=require('cheerio');
admin.initializeApp();
const ATHLETE_ID='375285';
const geocodeCache=new Map();
const knownCities={ventasso:{lat:44.365,lon:10.333},'castelvetro di modena':{lat:44.504,lon:10.946},'reggio nell\u0027emilia':{lat:44.698,lon:10.631},castellarano:{lat:44.555,lon:10.733},boretto:{lat:44.902,lon:10.555},novellara:{lat:44.845,lon:10.727},gualtieri:{lat:44.904,lon:10.629},rubiera:{lat:44.653,lon:10.782},modena:{lat:44.648,lon:10.926},casalgrande:{lat:44.598,lon:10.734},bologna:{lat:44.494,lon:11.342},parma:{lat:44.801,lon:10.328},ravenna:{lat:44.418,lon:12.204},milano:{lat:45.464,lon:9.19}};
async function geocode(city){if(geocodeCache.has(city))return geocodeCache.get(city);const normalized=city.toLowerCase().trim();if(knownCities[normalized]){geocodeCache.set(city,knownCities[normalized]);return knownCities[normalized]}const fallback={lat:44.65,lon:11.1};try{const r=await fetch(`https://photon.komoot.io/api/?limit=1&lang=it&q=${encodeURIComponent(`${city}, Italia`)}`,{headers:{'User-Agent':'RunMap/1.0'}});if(!r.ok)return fallback;const data=await r.json();const coordinates=data.features?.[0]?.geometry?.coordinates;const point=coordinates?{lat:Number(coordinates[1]),lon:Number(coordinates[0])}:fallback;geocodeCache.set(city,point);return point}catch(error){console.error(`Geocoding fallito per ${city}`,error);return fallback}}
async function suggestCities(query){const r=await fetch(`https://photon.komoot.io/api/?limit=6&lang=it&q=${encodeURIComponent(`${query}, Italia`)}`,{headers:{'User-Agent':'RunMap/1.0'}});if(!r.ok)throw new Error(`Photon ${r.status}`);const data=await r.json();return (data.features||[]).map(feature=>{const p=feature.properties;return {label:[p.name,p.city||p.town||p.village,p.state].filter((item,index,array)=>item&&array.indexOf(item)===index).join(', '),lat:feature.geometry.coordinates[1],lon:feature.geometry.coordinates[0]}})}
function parseTime(value){return value.replace(/\./g,':').match(/\b\d{2}:\d{2}:\d{2}\b/)?.[0]||'00:00:00'}
exports.citySuggestions=onRequest({cors:true,region:'europe-west1'},async(req,res)=>{if(req.method!=='GET')return res.status(405).json({error:'GET required'});if(!req.headers.authorization?.startsWith('Bearer '))return res.status(401).json({error:'Login richiesto'});try{const query=String(req.query.q||'').trim();if(query.length<3)return res.json({cities:[]});return res.json({cities:await suggestCities(query)})}catch(error){console.error(error);return res.status(502).json({error:'Suggerimenti non disponibili'})}});
exports.importRaces=onRequest({cors:true,region:'europe-west1',timeoutSeconds:60},async(req,res)=>{if(req.method!=='GET')return res.status(405).json({error:'GET required'});if(!req.headers.authorization?.startsWith('Bearer '))return res.status(401).json({error:'Login richiesto'});try{const response=await fetch(`https://www.irunning.it/atleta.php?id=${ATHLETE_ID}`,{headers:{'User-Agent':'RunMap/1.0'}});if(!response.ok)throw new Error(`iRunning ${response.status}`);const $=cheerio.load(await response.text());const races=[];$('#tab1 tbody tr').each((index,row)=>{const cells=$(row).find('td');if(cells.length<7)return;const dateRaw=$(cells[0]).text().trim();const parts=dateRaw.split('/');if(parts.length!==3)return;const city=$(cells[1]).text().trim().replace(/\s+/g,' ');const name=$(cells[2]).find('a').first().text().trim()||$(cells[2]).text().trim();const time=parseTime($(cells[6]).text().trim());const distanceMatch=name.match(/(\d+(?:[.,]\d+)?)\s*km/i);const distance=distanceMatch?Number(distanceMatch[1].replace(',','.')):null;races.push({id:`irunning-${ATHLETE_ID}-${index}-${parts.join('')}`,date:`${parts[2]}-${parts[1].padStart(2,'0')}-${parts[0].padStart(2,'0')}`,name,city,distance,time,lat:null,lon:null,notes:'',photos:[]})});for(const race of races){const point=await geocode(race.city);race.lat=point.lat;race.lon=point.lon}return res.json({athleteId:ATHLETE_ID,races})}catch(error){console.error(error);return res.status(502).json({error:'Importazione iRunning non riuscita'})}});
