const {onRequest}=require('firebase-functions/v2/https');
const admin=require('firebase-admin');
const cheerio=require('cheerio');
admin.initializeApp();
const ATHLETE_ID='375285';
const geocodeCache=new Map();
async function geocode(city){if(geocodeCache.has(city))return geocodeCache.get(city);const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=it&q=${encodeURIComponent(city)}`,{headers:{'User-Agent':'RunMap/1.0 contact:runmap@example.com'}});const data=await r.json();const point=data[0]?{lat:Number(data[0].lat),lon:Number(data[0].lon)}:{lat:44.65,lon:11.1};geocodeCache.set(city,point);return point}
function parseTime(value){return value.replace(/\./g,':').match(/\b\d{2}:\d{2}:\d{2}\b/)?.[0]||'00:00:00'}
exports.importRaces=onRequest({cors:true,region:'europe-west1',timeoutSeconds:60},async(req,res)=>{if(req.method!=='GET')return res.status(405).json({error:'GET required'});if(!req.headers.authorization?.startsWith('Bearer '))return res.status(401).json({error:'Login richiesto'});try{const response=await fetch(`https://www.irunning.it/atleta.php?id=${ATHLETE_ID}`,{headers:{'User-Agent':'RunMap/1.0'}});if(!response.ok)throw new Error(`iRunning ${response.status}`);const $=cheerio.load(await response.text());const races=[];$('#tab1 tbody tr').each((index,row)=>{const cells=$(row).find('td');if(cells.length<7)return;const dateRaw=$(cells[0]).text().trim();const parts=dateRaw.split('/');if(parts.length!==3)return;const city=$(cells[1]).text().trim().replace(/\s+/g,' ');const name=$(cells[2]).find('a').first().text().trim()||$(cells[2]).text().trim();const time=parseTime($(cells[6]).text().trim());const distanceMatch=name.match(/(\d+(?:[.,]\d+)?)\s*km/i);const distance=distanceMatch?Number(distanceMatch[1].replace(',','.')):null;races.push({id:`irunning-${ATHLETE_ID}-${index}-${parts.join('')}`,date:`${parts[2]}-${parts[1].padStart(2,'0')}-${parts[0].padStart(2,'0')}`,name,city,distance,time,lat:null,lon:null,notes:'',photos:[]})});for(const race of races){const point=await geocode(race.city);race.lat=point.lat;race.lon=point.lon}return res.json({athleteId:ATHLETE_ID,races})}catch(error){console.error(error);return res.status(502).json({error:'Importazione iRunning non riuscita'})}});
