const seedRaces=[
{id:1,date:'2025-10-12',name:'Maratona di Reggio Emilia',city:'Reggio Emilia',distance:42.195,time:'03:28:41',lat:44.698,lon:10.631},
{id:2,date:'2025-09-28',name:'Mezza Maratona di Bologna',city:'Bologna',distance:21.097,time:'01:35:22',lat:44.494,lon:11.342},
{id:3,date:'2025-09-07',name:'Corsa del Secchia',city:'Modena',distance:10,time:'00:42:18',lat:44.648,lon:10.926},
{id:4,date:'2025-06-15',name:'Run 5.000 Parco Nord',city:'Milano',distance:5,time:'00:19:44',lat:45.523,lon:9.207},
{id:5,date:'2025-05-25',name:'Ravenna Half Marathon',city:'Ravenna',distance:21.097,time:'01:38:09',lat:44.418,lon:12.204},
{id:6,date:'2025-04-13',name:'Vivicittà Reggio Emilia',city:'Reggio Emilia',distance:10,time:'00:44:02',lat:44.7,lon:10.63},
{id:7,date:'2024-11-03',name:'Maratona di Parma',city:'Parma',distance:42.195,time:'03:36:17',lat:44.801,lon:10.328},
{id:8,date:'2024-09-22',name:'Corri Cesenatico',city:'Cesenatico',distance:10,time:'00:46:30',lat:44.2,lon:12.4},
{id:9,date:'2024-06-02',name:'Strapanaro',city:'Modena',distance:5,time:'00:20:12',lat:44.648,lon:10.926},
{id:10,date:'2024-04-21',name:'Bologna Marathon',city:'Bologna',distance:42.195,time:'03:52:08',lat:44.494,lon:11.342},
{id:11,date:'2023-10-08',name:'Reggio Emilia Run',city:'Reggio Emilia',distance:10,time:'00:49:15',lat:44.698,lon:10.631}];
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, collection, getDocs, getDoc, setDoc, deleteDoc, doc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { getStorage, ref, uploadBytes, getDownloadURL, deleteObject } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js';
import { firebaseConfig } from './firebase-config.js';
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp),storage=getStorage(firebaseApp);let currentUser=null;let races=[];let map,markers=[];
const $=id=>document.getElementById(id);
async function saveRace(r){if(!currentUser)throw new Error('Utente non autenticato');await setDoc(doc(db,'users',currentUser.uid,'races',String(r.id)),r)}
const CACHE_MAX_AGE=24*60*60*1000;
async function loadRaces(){try{const [snap,metaSnap]=await Promise.all([getDocs(collection(db,'users',currentUser.uid,'races')),getDoc(doc(db,'users',currentUser.uid,'settings','sync'))]);races=snap.docs.map(x=>x.data());const last=metaSnap.exists()?metaSnap.data().lastImportedAt:races.reduce((v,r)=>Math.max(v,r.importedAt||0),0);setSyncStatus(last);render();if(!races.length||!last||Date.now()-last>CACHE_MAX_AGE)importRaces({background:true})}catch(error){console.error('Firestore load failed',error);races=[];render();toast('Impossibile leggere Firestore: controlla le regole del database')}}
function setSyncStatus(timestamp,loading=false){$('syncStatus').textContent=loading?`Aggiornamento in corso · ${timestamp?new Date(timestamp).toLocaleString('it-IT',{dateStyle:'short',timeStyle:'short'}):'prima sincronizzazione'}`:timestamp?`Ultimo aggiornamento ${new Date(timestamp).toLocaleString('it-IT',{dateStyle:'short',timeStyle:'short'})}`:'Nessuna sincronizzazione'}
async function importRaces(options={}){const button=$('importBtn');if(button.disabled&&!options.background)return;if(!options.background){button.disabled=true;button.classList.add('loading');button.innerHTML='<span class="spinner" aria-hidden="true"></span> Importazione in corso...'}const previousSync=races.reduce((v,r)=>Math.max(v,r.importedAt||0),0);setSyncStatus(previousSync,true);try{const token=await auth.currentUser.getIdToken();const response=await fetch(`${window.RUNMAP_API_URL||''}/importRaces`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(`Import HTTP ${response.status}`);const data=await response.json();const importedAt=Date.now();let saved=0;for(const imported of data.races){const previous=races.find(old=>String(old.id)===String(imported.id));await saveRace({...imported,notes:previous?.notes||'',photos:previous?.photos||[],importedAt});saved++}await setDoc(doc(db,'users',currentUser.uid,'settings','sync'),{lastImportedAt:importedAt,raceCount:saved});await loadRacesWithoutImport();setSyncStatus(importedAt);if(!options.background)toast(`${saved} gare importate e sincronizzate`)}catch(error){console.error('Import failed',error);if(!options.background)toast(`Importazione non riuscita: ${error.code||error.message}`);setSyncStatus(previousSync)}finally{if(!options.background){button.disabled=false;button.classList.remove('loading');button.innerHTML='<span>＋</span> Importa gare'}}}
async function loadRacesWithoutImport(){const snap=await getDocs(collection(db,'users',currentUser.uid,'races'));races=snap.docs.map(x=>x.data());render()}
function formatDate(d){return new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00')).replace('.','').toUpperCase()}
function render(){const sort=$('sortSelect').value;let list=[...races];if(sort==='newest')list.sort((a,b)=>b.date.localeCompare(a.date));if(sort==='oldest')list.sort((a,b)=>a.date.localeCompare(b.date));if(sort==='distance')list.sort((a,b)=>b.distance-a.distance);$('raceList').innerHTML=list.map(r=>`<div class="race-row" data-id="${r.id}"><div class="race-date">${formatDate(r.date)}<span>${new Date(r.date+'T12:00:00').toLocaleDateString('it-IT',{weekday:'long'})}</span></div><div class="race-name">${r.name}</div><div class="race-city">${r.city}</div><div class="race-distance">${(r.distance==null?'Da inserire':r.distance.toFixed(r.distance%1?3:0)+' km')}</div><div class="race-time">${r.time}</div><button class="delete-btn" data-delete="${r.id}" aria-label="Elimina ${r.name}">♲</button></div>`).join('')||'<p class="intro">Nessuna gara archiviata.</p>';$('archiveCount').textContent=`(${races.length})`;$('raceCount').textContent=`${races.length} gare`;updatePB();renderMarkers();document.querySelectorAll('.race-row').forEach(row=>row.addEventListener('click',e=>{if(!e.target.closest('[data-delete]'))openModal(row.dataset.id)}));document.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const race=races.find(r=>String(r.id)===String(btn.dataset.delete));if(!race)return;races=races.filter(r=>String(r.id)!==String(btn.dataset.delete));deleteDoc(doc(db,'users',currentUser.uid,'races',String(race.id))).then(()=>{render();toast('Gara eliminata')}).catch(error=>{console.error('Delete failed',error);toast('Eliminazione non riuscita')}) }));}
function seconds(t){let a=t.split(':').map(Number);return a[0]*3600+a[1]*60+a[2]}
function updatePB(){[5,10,21,42].forEach(k=>{let found=races.filter(r=>Math.abs(r.distance-k)<1).sort((a,b)=>seconds(a.time)-seconds(b.time))[0];$(`pb${k}`).textContent=found?.time||'—';$(`race${k}`).textContent=found?`${formatDate(found.date)} · ${found.name}`:'Nessun record'})}
function renderMarkers(){markers.forEach(m=>m.remove());markers=[];races.forEach(r=>{const missingDistance=r.distance==null||!Number.isFinite(Number(r.distance));let icon=L.divIcon({className:`custom-pin${missingDistance?' missing-distance':''}`,html:'<span></span>',iconSize:[18,18],iconAnchor:[9,9]});let m=L.marker([r.lat,r.lon],{icon}).addTo(map).bindPopup(`<div class="popup-title">${r.name}</div><div class="popup-meta">${formatDate(r.date)} · ${(r.distance==null?'—':r.distance.toFixed(1))} km · ${r.time}</div>`);markers.push(m)})}
function openModal(id){let r=races.find(x=>String(x.id)===String(id));if(!r)return;$('modalTitle').textContent='Modifica gara';$('raceId').value=r.id;$('raceName').value=r.name;$('raceDate').value=r.date;$('raceDistance').value=r.distance;$('raceTime').value=r.time;$('raceCity').value=r.city;$('raceNotes').value=r.notes||'';$('photoPreview').innerHTML=(r.photos||[]).map(p=>`<img src="${p}" alt="Foto gara">`).join('');$('modal').classList.add('open')}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
let cityTimer;
async function suggestCities(){const value=$('raceCity').value.trim();if(value.length<3){$('citySuggestions').innerHTML='';$('cityStatus').textContent='Scrivi almeno 3 caratteri per ricevere suggerimenti';$('cityStatus').classList.remove('active');return}$('cityStatus').textContent='Ricerca località...';clearTimeout(cityTimer);cityTimer=setTimeout(async()=>{try{const response=await fetch(`https://photon.komoot.io/api/?limit=6&lang=it&q=${encodeURIComponent(`${value}, Italia`)}`);if(!response.ok)throw new Error('Geocoding failed');const data=await response.json();$('citySuggestions').innerHTML=(data.features||[]).map(feature=>{const p=feature.properties;const label=[p.name,p.city||p.town||p.village,p.state].filter((item,index,array)=>item&&array.indexOf(item)===index).join(', ');return `<option value="${label.replace(/"/g,'&quot;')}" data-lat="${feature.geometry.coordinates[1]}" data-lon="${feature.geometry.coordinates[0]}"></option>`}).join('');$('cityStatus').textContent=data.features?.length?'Seleziona una località per migliorare il pin':'Nessun suggerimento trovato';$('cityStatus').classList.toggle('active',!!data.features?.length)}catch(error){$('cityStatus').textContent='Suggerimenti non disponibili; puoi inserire la città manualmente'}} ,350)}
function openNewRace(){if(!currentUser){toast('Accedi con Google per aggiungere una gara');return}const id=`manual-${Date.now()}`;$('modalTitle').textContent='Aggiungi gara';$('raceId').value=id;$('raceName').value='';$('raceDate').value='';$('raceDistance').value='';$('raceTime').value='';$('raceCity').value='';$('raceCity').dataset.lat='';$('raceCity').dataset.lon='';$('raceNotes').value='';$('racePhotos').value='';$('photoPreview').innerHTML='';$('modal').classList.add('open')}
function init(){map=L.map('map',{zoomControl:true}).setView([44.65,11.1],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);render();$('sortSelect').onchange=render;$('themeToggle').onclick=()=>document.body.classList.toggle('dark');$('resetMap').onclick=()=>{if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.18))};$('closeModal').onclick=()=> $('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.remove('open')};$('raceForm').onsubmit=async e=>{e.preventDefault();const button=$('saveRaceBtn');let r=races.find(x=>String(x.id)===String($('raceId').value));const isNew=!r;if(isNew){r={id:$('raceId').value,photos:[]};races.push(r)}const distance=Number($('raceDistance').value);if(!Number.isFinite(distance)||distance<=0){if(isNew)races=races.filter(item=>item.id!==r.id);toast('Inserisci una distanza valida');return}const original={...r};Object.assign(r,{name:$('raceName').value.trim(),date:$('raceDate').value,distance,time:$('raceTime').value.trim(),city:$('raceCity').value.trim(),notes:$('raceNotes').value,lat:Number($('raceCity').dataset.lat)||r.lat||44.65,lon:Number($('raceCity').dataset.lon)||r.lon||11.1});const files=[...$('racePhotos').files].slice(0,5-(r.photos||[]).length);button.disabled=true;button.textContent='Salvataggio...';try{const urls=await Promise.all(files.map((file,i)=>{const location=ref(storage,`users/${currentUser.uid}/races/${r.id}/${Date.now()}-${i}-${file.name}`);return uploadBytes(location,file).then(()=>getDownloadURL(location))}));r.photos=[...(r.photos||[]),...urls].slice(0,5);await saveRace(r);$('modal').classList.remove('open');$('racePhotos').value='';render();toast('Modifiche salvate e sincronizzate')}catch(error){if(isNew)races=races.filter(item=>item.id!==r.id);else Object.assign(r,original);console.error('Save failed',error);toast(error.code==='permission-denied'?'Permesso Firestore/Storage negato':'Salvataggio non riuscito')}finally{button.disabled=false;button.textContent='Salva modifiche'}};$('importBtn').onclick=importRaces;$('addRaceBtn').onclick=openNewRace;$('raceCity').addEventListener('input',suggestCities);$('raceCity').addEventListener('change',()=>{const option=[...$('citySuggestions').options].find(item=>item.value===$('raceCity').value);if(option){$('raceCity').dataset.lat=option.dataset.lat;$('raceCity').dataset.lon=option.dataset.lon;$('cityStatus').textContent='Località selezionata: pin geolocalizzato';}});$('loginBtn').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider());$('profileBtn').onclick=e=>{e.stopPropagation();$('profileMenu').classList.toggle('open')};$('logoutBtn').onclick=()=>signOut(auth);document.addEventListener('click',()=>$('profileMenu').classList.remove('open'));}
onAuthStateChanged(auth,user=>{currentUser=user;if(user){const name=user.displayName||'Utente';$('profileName').textContent=name;$('profileEmail').textContent=user.email||'';$('avatarInitials').textContent=name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();if(user.photoURL){$('avatarPhoto').src=user.photoURL;$('avatarPhoto').hidden=false;$('avatarInitials').hidden=true}$('authGate').classList.add('hidden');loadRaces()}else{$('authGate').classList.remove('hidden')}})
if(document.readyState==='loading'){window.addEventListener('DOMContentLoaded',init,{once:true})}else{init()}