import {getApps,getApp,initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,setDoc,deleteDoc} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let races=[];
function modal(){if($('futureModal'))return;const m=document.createElement('div');m.className='modal-backdrop';m.id='futureModal';m.innerHTML='<div class="modal"><button class="close-modal" id="closeFuture" type="button">x</button><p class="eyebrow">GARA FUTURA</p><h2 id="futureTitle">Nuova gara</h2><form id="futureForm"><input type="hidden" id="futureId"><label>Nome gara<input id="futureName" required></label><div class="form-row"><label>Data<input id="futureDate" type="date" required></label><label>Distanza (km)<input id="futureDistance" type="number" min="0.1" step="0.1" required></label></div><label>Luogo<input id="futurePlace" required></label><label>Costo (EUR)<input id="futureCost" type="number" min="0" step="0.01"></label><div class="future-checks"><label><input id="futureRegistered" type="checkbox"> Iscritto</label><label><input id="futureMedal" type="checkbox"> Medaglia prevista</label><label><input id="futureGp" type="checkbox"> GP</label></div><button class="primary full" type="submit">Salva gara</button></form></div>';document.body.appendChild(m);$('closeFuture').onclick=()=>m.classList.remove('open');$('futureForm').onsubmit=save}
function openFuture(r){modal();$('futureTitle').textContent=r?'Modifica gara':'Nuova gara';$('futureId').value=r?.id||`future-${Date.now()}`;$('futureName').value=r?.name||'';$('futureDate').value=r?.date||'';$('futureDistance').value=r?.distance||'';$('futurePlace').value=r?.place||'';$('futureCost').value=r?.cost||'';$('futureRegistered').checked=!!r?.registered;$('futureMedal').checked=!!r?.medal;$('futureGp').checked=!!r?.gp;$('futureModal').classList.add('open')}
async function save(e){e.preventDefault();const r={id:$('futureId').value,name:$('futureName').value.trim(),date:$('futureDate').value,distance:Number($('futureDistance').value),place:$('futurePlace').value.trim(),cost:Number($('futureCost').value)||0,registered:$('futureRegistered').checked,medal:$('futureMedal').checked,gp:$('futureGp').checked};await setDoc(doc(db,'users',auth.currentUser.uid,'futureRaces',r.id),r);$('futureModal').classList.remove('open');await load()}
async function remove(e){e.stopPropagation();const id=e.currentTarget.dataset.remove;if(!confirm('Eliminare questa gara futura?'))return;await deleteDoc(doc(db,'users',auth.currentUser.uid,'futureRaces',id));await load()}
async function load(){const snap=await getDocs(collection(db,'users',auth.currentUser.uid,'futureRaces'));const today=new Date().toISOString().slice(0,10);races=snap.docs.map(x=>x.data()).map(r=>{const status=r.date<today?'passata':'in programma';if(r.status!==status)setDoc(doc(db,'users',auth.currentUser.uid,'futureRaces',String(r.id)),{status},{merge:true});return {...r,status}}).sort((a,b)=>a.date.localeCompare(b.date));const list=$('futureList');list.innerHTML=races.map(r=>`<div class="future-row" data-id="${r.id}"><div><strong>${r.name}</strong><small>${r.date} - ${r.place} - ${r.distance} km</small></div><span>${r.registered?'Iscritto':'Non iscritto'}<br>Medaglia: ${r.medal?'Si':'No'}<br>GP: ${r.gp?'Si':'No'}<br><b>${r.status==='passata'?'Passata':'In programma'}</b></span><button class="delete-btn" type="button" data-remove="${r.id}" aria-label="Elimina gara">x</button></div>`).join('')||'<p class="intro">Nessuna gara futura inserita.</p>';document.querySelectorAll('.future-row').forEach(row=>row.onclick=e=>{if(!e.target.closest('[data-remove]'))openFuture(races.find(r=>String(r.id)===row.dataset.id))});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=remove)}
function init(){const section=document.createElement('section');section.className='macro-section';section.innerHTML='<button class="macro-button" type="button" aria-expanded="false" aria-controls="futureContent">Gare future <span>+</span></button><div class="macro-content" id="futureContent"><div class="future-head"><button class="secondary" id="addFuture" type="button">+ Crea nuova nota</button></div><div id="futureList" class="future-list"></div></div>';const main=document.querySelector('main'),workoutsSection=document.querySelector('[aria-controls="workoutsPlaceholderContent"]')?.closest('.macro-section');main.insertBefore(section,workoutsSection?.nextElementSibling||document.querySelector('.races-section'));section.querySelector('.macro-button').onclick=()=>{const b=section.querySelector('.macro-button'),open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));$('futureContent').classList.toggle('expanded',!open)};$('addFuture').onclick=()=>openFuture();modal();load()}
onAuthStateChanged(auth,user=>{if(user&&!document.querySelector('[aria-controls="futureContent"]'))init()});
