import {initializeApp,getApps,getApp} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,setDoc,deleteDoc} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let notes=[];const $=id=>document.getElementById(id);
const css=`.planned-section{margin:0 0 14px}.planned-section .macro-content{padding:20px}.planned-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.planned-head h2{font:600 18px 'Space Grotesk';margin:0}.planned-list{display:flex;flex-direction:column;gap:8px}.planned-row{display:grid;grid-template-columns:1fr auto 30px;gap:14px;align-items:center;padding:14px 16px;background:var(--surface);border:1px solid var(--line);border-radius:7px;cursor:pointer}.planned-row strong,.planned-row small{display:block}.planned-row strong{font-size:13px}.planned-row small{font-size:11px;color:var(--muted);margin-top:4px}.planned-row>span{font-size:10px;color:var(--lime-dark);font-weight:700}.planned-checks{display:flex;gap:16px;margin:8px 0 16px}.planned-checks label{display:flex;align-items:center;gap:5px;color:var(--ink);font-size:12px}.planned-checks input{width:auto;margin:0}@media(max-width:700px){.planned-head{align-items:flex-start;gap:10px}.planned-head h2{font-size:16px}.planned-row{grid-template-columns:1fr 28px;padding:13px}.planned-row>span{display:none}.planned-checks{flex-direction:column;gap:9px}}`;
function addStyle(){const s=document.createElement('style');s.textContent=css;document.head.appendChild(s)}
function inject(){const section=document.createElement('section');section.className='planned-section macro-section';section.innerHTML=`<button class="macro-button" type="button" aria-expanded="false" aria-controls="plannedContent">Gare in programma <span>+</span></button><div class="macro-content" id="plannedContent"><div class="planned-head"><h2>Prossime gare</h2><button class="secondary" id="newPlanned" type="button">+ Crea nuova nota</button></div><div id="plannedList" class="planned-list"></div></div>`;const main=document.querySelector('main');main.insertBefore(section,main.querySelector('.races-section')||null);const modal=document.createElement('div');modal.className='modal-backdrop';modal.id='plannedModal';modal.innerHTML=`<div class="modal"><button class="close-modal" id="closePlanned" type="button">x</button><p class="eyebrow">GARA IN PROGRAMMA</p><h2 id="plannedTitle">Crea nuova nota</h2><form id="plannedForm"><input type="hidden" id="plannedId"><label>Nome gara<input id="plannedName" required></label><div class="form-row"><label>Data<input id="plannedDate" type="date" required></label><label>Distanza (km)<input id="plannedDistance" type="number" min="0.1" step="0.1" required></label></div><label>Luogo<input id="plannedPlace" required></label><label>Costo (EUR)<input id="plannedCost" type="number" min="0" step="0.01" placeholder="0"></label><div class="planned-checks"><label><input id="plannedRegistered" type="checkbox"> Iscritto</label><label><input id="plannedMedal" type="checkbox"> Medaglia prevista</label><label><input id="plannedGp" type="checkbox"> G.P.</label></div><button class="primary full" type="submit">Salva nota</button></form></div>`;document.body.appendChild(modal);$('plannedContent').previousElementSibling.onclick=()=>{const b=$('plannedContent').previousElementSibling,o=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!o));$('plannedContent').classList.toggle('expanded',!o)};$('newPlanned').onclick=newNote;$('closePlanned').onclick=()=>modal.classList.remove('open');$('plannedForm').onsubmit=saveNote}
function newNote(){$('plannedTitle').textContent='Crea nuova nota';$('plannedId').value='planned-'+Date.now();['plannedName','plannedDate','plannedDistance','plannedPlace','plannedCost'].forEach(id=>$(id).value='');['plannedRegistered','plannedMedal','plannedGp'].forEach(id=>$(id).checked=false);$('plannedModal').classList.add('open')}
function editNote(id){const r=notes.find(x=>String(x.id)===String(id));if(!r)return;$('plannedTitle').textContent='Modifica gara';$('plannedId').value=r.id;$('plannedName').value=r.name;$('plannedDate').value=r.date;$('plannedDistance').value=r.distance;$('plannedPlace').value=r.place;$('plannedCost').value=r.cost||'';$('plannedRegistered').checked=!!r.registered;$('plannedMedal').checked=!!r.medal;$('plannedGp').checked=!!r.gp;$('plannedModal').classList.add('open')}
async function load(){const snap=await getDocs(collection(db,'users',auth.currentUser.uid,'plannedNotes'));notes=snap.docs.map(x=>x.data());render()}
function render(){$('plannedList').innerHTML=notes.sort((a,b)=>a.date.localeCompare(b.date)).map(r=>`<div class="planned-row" data-id="${r.id}"><div><strong>${r.name}</strong><small>${r.date} Ã‚Â· ${r.place} Ã‚Â· ${r.distance} km Ã‚Â· ${Number(r.cost||0).toFixed(2)} EUR</small></div><span>${r.registered?'Iscritto':'Da iscrivere'} Ã‚Â· Medaglia: ${r.medal?'Si':'No'} Ã‚Â· G.P.: ${r.gp?'Si':'No'}</span><button class="delete-btn" type="button" data-delete="${r.id}" aria-label="Elimina gara">x</button></div>`).join('')||'<p class="intro">Nessuna gara in programma.</p>';document.querySelectorAll('.planned-row[data-id]').forEach(e=>e.onclick=()=>editNote(e.dataset.id));document.querySelectorAll('[data-delete]').forEach(e=>e.onclick=async ev=>{ev.stopPropagation();if(!confirm('Eliminare questa nota?'))return;await deleteDoc(doc(db,'users',auth.currentUser.uid,'plannedNotes',e.dataset.delete));await load()})}
async function saveNote(e){e.preventDefault();const id=$('plannedId').value;const race={id,name:$('plannedName').value.trim(),date:$('plannedDate').value,distance:Number($('plannedDistance').value),place:$('plannedPlace').value.trim(),cost:Number($('plannedCost').value)||0,registered:$('plannedRegistered').checked,medal:$('plannedMedal').checked,gp:$('plannedGp').checked};await setDoc(doc(db,'users',auth.currentUser.uid,'plannedNotes',id),race);$('plannedModal').classList.remove('open');await load()}
addStyle();onAuthStateChanged(auth,user=>{if(user){if(!document.querySelector('.planned-section'))inject();load()}});
