import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, collection, getDocs, setDoc, deleteDoc, doc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let user=null, shoes=[], workouts=[];
const byId=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const km=n=>Number(n||0).toLocaleString('it-IT',{maximumFractionDigits:1});
function ensurePanels(){
  const shoesBox=byId('shoesContent'), workoutsBox=byId('workoutsContent'); if(!shoesBox||!workoutsBox)return;
  shoesBox.innerHTML='<div class="feature-toolbar"><p>Monitora chilometri, usura e stato delle tue scarpe.</p><button class="secondary" id="addShoeFeature">+ Aggiungi scarpa</button></div><div id="shoeCards" class="shoe-cards"></div>';
  workoutsBox.innerHTML='<div class="feature-toolbar"><p>Sincronizza le attività di corsa con Strava o aggiungile manualmente.</p><div class="feature-actions"><button class="secondary" id="connectStrava">Collega Strava</button><button class="secondary" id="addWorkoutFeature">+ Attività manuale</button></div></div><div id="workoutList" class="workout-list"></div>';
  byId('addShoeFeature').onclick=()=>shoeDialog(); byId('addWorkoutFeature').onclick=()=>workoutDialog(); byId('connectStrava').onclick=connectStrava;
}
async function load(){ if(!user)return; const [ss,ws]=await Promise.all([getDocs(collection(db,'users',user.uid,'shoes')),getDocs(collection(db,'users',user.uid,'workouts'))]); shoes=ss.docs.map(x=>x.data());workouts=ws.docs.map(x=>x.data());render(); }
function render(){
  const cards=byId('shoeCards'), list=byId('workoutList'); if(!cards||!list)return;
  cards.innerHTML=shoes.length?shoes.map(s=>{const used=workouts.filter(w=>w.shoeId===s.id).reduce((a,w)=>a+Number(w.distance||0),0), max=Number(s.maxKm)||800, pct=Math.min(100,used/max*100), state=pct>=100?'Da sostituire':pct>=80?'Quasi esaurita':'In uso';return `<article class="shoe-card"><div class="shoe-card-head"><div><span class="eyebrow">${esc(state)}</span><h3>${esc(s.name)}</h3><small>${esc(s.brand||'')} ${esc(s.model||'')}</small></div><button class="icon-action" data-delete-shoe="${esc(s.id)}" aria-label="Elimina scarpa">×</button></div><div class="shoe-km"><strong>${km(used)} km</strong><span>su ${km(max)} km</span></div><div class="wear-bar"><i style="width:${pct}%"></i></div><div class="shoe-card-foot"><span>${Math.max(0,max-used).toLocaleString('it-IT',{maximumFractionDigits:1})} km rimanenti</span><button class="text-action" data-edit-shoe="${esc(s.id)}">Modifica</button></div></article>`}).join(''):'<p class="intro">Nessuna scarpa registrata. Aggiungi la tua prima scarpa.</p>';
  list.innerHTML=workouts.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(w=>`<article class="workout-row"><div><strong>${esc(w.name)}</strong><small>${esc(w.date)} · ${esc(w.source==='strava'?'Strava':'Manuale')}</small></div><b>${km(w.distance)} km</b><span>${esc(shoes.find(s=>s.id===w.shoeId)?.name||'Nessuna scarpa')}</span><button class="icon-action" data-delete-workout="${esc(w.id)}" aria-label="Elimina attività">×</button></article>`).join('')||'<p class="intro">Nessuna attività registrata.</p>';
  document.querySelectorAll('[data-delete-shoe]').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare questa scarpa?')){await deleteDoc(doc(db,'users',user.uid,'shoes',b.dataset.deleteShoe));await load()}});document.querySelectorAll('[data-edit-shoe]').forEach(b=>b.onclick=()=>shoeDialog(shoes.find(s=>s.id===b.dataset.editShoe)));document.querySelectorAll('[data-delete-workout]').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare questa attività?')){await deleteDoc(doc(db,'users',user.uid,'workouts',b.dataset.deleteWorkout));await load()}});
}
function dialog(title,body,submit){const wrap=document.createElement('div');wrap.className='feature-modal';wrap.innerHTML=`<div class="feature-dialog"><button class="feature-close">×</button><p class="eyebrow">${title}</p><form>${body}<button class="primary full" type="submit">Salva</button></form></div>`;document.body.append(wrap);wrap.querySelector('.feature-close').onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();await submit(new FormData(e.target));wrap.remove();await load()}}
function shoeDialog(item={}){dialog(item.id?'MODIFICA SCARPA':'NUOVA SCARPA',`<label>Nome scarpa<input name="name" required value="${esc(item.name)}" placeholder="es. Pegasus 41"></label><div class="form-row"><label>Marca<input name="brand" value="${esc(item.brand)}"></label><label>Modello<input name="model" value="${esc(item.model)}"></label></div><label>Chilometraggio massimo (km)<input name="maxKm" type="number" min="1" value="${item.maxKm||800}" required></label>`,async f=>{const id=item.id||`shoe-${Date.now()}`;await setDoc(doc(db,'users',user.uid,'shoes',id),{id,name:f.get('name').trim(),brand:f.get('brand').trim(),model:f.get('model').trim(),maxKm:Number(f.get('maxKm'))})}
function workoutDialog(){const options=shoes.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');dialog('NUOVA ATTIVITÀ',`<label>Nome attività<input name="name" required placeholder="es. Corsa mattutina"></label><div class="form-row"><label>Data<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Distanza (km)<input name="distance" type="number" step="0.1" min="0.1" required></label></div><label>Scarpa associata<select name="shoeId"><option value="">Nessuna scarpa</option>${options}</select></label>`,async f=>{const id=`workout-${Date.now()}`;await setDoc(doc(db,'users',user.uid,'workouts',id),{id,name:f.get('name').trim(),date:f.get('date'),distance:Number(f.get('distance')),shoeId:f.get('shoeId')||'',source:'manual'})})}
async function connectStrava(){try{const token=await user.getIdToken();const response=await fetch(`${window.RUNMAP_API_URL||''}/stravaAuth`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Collegamento Strava non disponibile');const data=await response.json();window.location.href=data.authorizationUrl}catch(error){console.error('Strava connection failed',error);alert('Collegamento a Strava non disponibile')}}
 onAuthStateChanged(auth,u=>{user=u;if(u){ensurePanels();load();const params=new URLSearchParams(location.search);if(params.get('strava')==='connected')alert(`${params.get('imported')||0} attività Strava importate`);if(params.has('strava'))history.replaceState({},'',location.pathname)}});

ensurePanels();
